package com.bikcodeh.newsapp.network

const val FILE_SUCCESS_NEWS_RESPONSE = "success_news_response.json"
const val FILE_SUCCESS_EMPTY_RESPONSE = "success_empty_response.json"
const val FILE_SUCCESS_NEWS_BY_SOURCE_RESPONSE = "success_news_by_source_response.json"
const val FILE_SUCCESS_NEWS_BY_SOURCE_TALK_SPORT_RESPONSE = "success_news_by_source_talksport_response.json"
const val FILE_SUCCESS_NEWS_BY_CATEGORY_BUSINESS_RESPONSE = "success_news_by_category_business_response.json"
const val FILE_SUCCESS_NEWS_BY_CATEGORY_GENERAL_RESPONSE = "success_news_by_category_general_response.json"